version: "3.8"

services:
  # ---------------------------------------------
  # Service 1: The API
  # ---------------------------------------------
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
      - app-data:/storage
    depends_on:
      - redis
      - db
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=doc_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  # ---------------------------------------------
  # Service 2: The Worker
  # ---------------------------------------------
  worker:
    build: ./workers
    volumes:
      - ./workers:/app
      - /app/node_modules
      - app-data:/storage
    command: node index.js
    depends_on:
      - redis
      - db
      - gotenberg
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=doc_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  gotenberg:
    image: gotenberg/gotenberg:7
    ports:
      - "3001:3000"

  # ---------------------------------------------
  # Service 3: Redis (Queue)
  # ---------------------------------------------
  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - "6379:6379"

  # ---------------------------------------------
  # Service 4: PostgreSQL (Database)
  # ---------------------------------------------
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=doc_db
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

# ---------------------------------------------
# Volumes
# ---------------------------------------------
volumes:
  app-data: # Shared file storage
  pg-data: # Database storage
